### PR TITLE
Added requirements.txt

### PR DESCRIPTION
**Pull request by Scot-Survivor**
Fixed some basic PEP8 Formatting errors, checked and fixed giftit.py

### CODE REVIEW

**Review by H4CKY54CK — CHANGES_REQUESTED** [review]
Revert the changes to `gifit.py`, `sliceit.py`, and `spriteit.py` so I can accept the other changes. All three of those need to be looked into further by myself so I can decide what I even want to do with them.

Thanks for everything else, though.

**Comment by H4CKY54CK** [comment]
I also made some major revisions to `utils.py`. I'm not sure why I decided to do it in Github's editor, though.

**Comment by Scot-Survivor** [comment]
> Revert the changes to `gifit.py`, `sliceit.py`, and `spriteit.py` so I can accept the other changes. All three of those need to be looked into further by myself so I can decide what I even want to do with them.
> 
> 
> 
> Thanks for everything else, though.

Alright I'll handle that in a couple hours. Thank you man.

**Comment by Scot-Survivor** [comment]
Okay so it should be good to go. Let me know if there's any other errors, apologises about the confusion between pull requests

**Review by H4CKY54CK — CHANGES_REQUESTED** [review]
Remove the 3 comments in `cli.py`.
Revert changes to `spriteit.py` (I have a version I'm replacing it with)

I'll redo my changes in a separate commit, and we'll get everything cleaned up and back on track.

**Review by H4CKY54CK — APPROVED** [review]
Thanks for all this!

Just to get everything back in order, some of the more minor changes in your PR might get changed in my PR that follows.

**Pull request merged**
